### ISSUE TITLE
Hackage release

### ISSUE THREAD

**Issue by wz1000** [wz1000/HieDb#24]
This issue is to track the progress of the `hiedb` hackage release.

From my point of view, we are pretty much ready. @jhrcek do you have anything in the pipeline that you would like to be included?

If not, I will finalize the release.

PS: @jhrcek, could I have your hackage username so I can add you as a maintainer?

**Comment by jhrcek** [comment]
@wz1000 I don't have anything at the moment regarding this project, I'm winding down as the christmas/end of year holidays are coming. But I'll get back to this in the future.
My hackage username is jhrcek and I'm ok with being added as a maintainer of this project.

**Comment by wz1000** [comment]
Uploaded here: https://hackage.haskell.org/package/hiedb-0.1.0.0

I really appreciate all your help, @jhrcek!
