### ISSUE TITLE
Add ability to peek at source surrounding a reference.

### ISSUE THREAD

**Issue by AndreasPK** [wz1000/HieDb#5]
I looked up a definition:

```
$ hiedb name-refs threadDelay
System.Win32.File:344:25-344:36
System.Win32.Console.HWND:13:39-13:50
System.Win32.Console.HWND:32:9-32:20
System.Timeout:136:43-136:54
GHC.Event.Windows.Thread:6:5-6:16
GHC.Event.Windows.Thread:25:1-25:12
GHC.Event.Windows.Thread:26:1-26:12
GHC.Conc:56:11-56:22
GHC.Conc.Windows:27:10-27:21
GHC.Conc.Windows:105:1-105:12
GHC.Conc.Windows:106:1-106:12
GHC.Conc.Windows:106:15-106:32
GHC.Conc.Windows:106:37-106:54
GHC.Conc.POSIX:27:10-27:21
GHC.Conc.POSIX:105:1-105:12
GHC.Conc.POSIX:106:1-106:12
GHC.Conc.IO:35:11-35:22
GHC.Conc.IO:203:1-203:12
GHC.Conc.IO:204:1-204:12
GHC.Conc.IO:206:25-206:44
GHC.Conc.IO:207:25-207:44
Control.Concurrent:60:9-60:20
Common:11:35-11:46
Common:123:19-123:30
```

It seemed quite natural to want to see how they are used as a next step. But currently hiedb doesn't provide this ability.

What I would hope for is something like:

hiedb name-refs threadDelay [-v] [-n]

Where -v would print the using line of code in combination with file/position.
-n would expand this to up to n surrounding lines.

Granted if that would be a major undertaking then it's not worthwhile. But if it's simple it would be great to have.

**Comment by wz1000** [comment]
Should be pretty straightforward since we have the source.

If you can get https://github.com/wz1000/hie-lsp  working, it should let you browse references in vscode.

I am currently in the middle of a rewrite of `haskell-lsp`, when that is done I will try to put `hie-lsp` back in a usable state.

**Comment by wz1000** [comment]
Fixed in https://github.com/wz1000/HieDb/commit/c3c72c8cab51424aa7d19a4fa035843968b9228a

![2021-01-21-010156_grab](https://user-images.githubusercontent.com/4812498/105227657-92690200-5b87-11eb-9d15-2a4a62e7f230.png)
