### ISSUE TITLE
add hackage/shell.nix (or flake) support

### ISSUE THREAD

**Issue by teto** [wz1000/HieDb#7]
Hi,

I want to use this program to help me debug some .hie files but I have some issues indexing my hie files.
Both the .hie file and hiedb should have been compiled with ghc 8.8.3 yet I get:
`IncompatibleSchemaVersion {expectedVersion = 19998083, gotVersion = 19998084}`
if I use ghc884 for hiedb, I get.
`readHieFile: hie file versions don't match for file: /home/teto/user_cache/f3097620197e6c203645e1230d1ae88c/execroot/toplevel_workspace/bazel-out/Porcupine.hie Expected 8084 but got 8083`. Maybe my .hie files were compiled with different compilers but that would be suprising :s 

It would make it easier to integrate in my project if it was on hackage or available as a nix package.
Cheers

**Comment by wz1000** [comment]
For the first error, you need to delete your default hiedb (should be in ~/.local/share). I can fix such errors by adding the schema version to the filename of the local db. Thanks for the bug report!

I will upload this to hackage soon.

**Comment by teto** [comment]
ha that was a hard one. Wouldn't naming the db ~/.local/share/default_883.hiedb  avoid that ?

Cool for hackage !

**Comment by wz1000** [comment]
yeah, that what I'll do. I just introduced the schema recently, and didn't notice this bug since I've been using it with `ghcide`, which manages its own database location and names it properly according to the ghc version.

**Comment by wz1000** [comment]
Fixed one part of this issue in https://github.com/wz1000/HieDb/commit/bb789d3ea09d040a980dbeb92d8749510c958125

**Comment by wz1000** [comment]
Closing in favor of #24
